#!/bin/bash

alias l="ls -laFbh"

alias vi=vim
alias vimc="vim -u NONE -N"

alias ga='git add'
alias gaa='git add -A'
alias gp='git push'
alias gl="git log --all --graph --pretty=format:'%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
alias gs='git status'
alias gd='git diff'
alias gdc='git diff --cached'
alias gm='git commit -m'
alias gma='git commit -am'
alias gb='git branch'
alias gc='git checkout'
alias gra='git remote add'
alias grr='git remote rm'
alias gpu='git pull'
alias gcl='git clone'

alias mv="mv -i"
alias cp="cp -i"
alias rm="rm -i"

alias speedtest="wget -O /dev/null http://cachefly.cachefly.net/100mb.test"

