#!/bin/bash

# Editors.
export EDITOR="vim"
export VISUAL="vim"

#LS Colors
export CLICOLOR=1

export LC_CTYPE=$LANG

#
# Color grep results
# Examples: http://rubyurl.com/ZXv
#
# export GREP_OPTIONS='--color=auto'
export GREP_COLOR='1;32'

export PATH=~/.bin:$PATH
